name: Add commit messages to PR description

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit messages
        id: commits
        run: |
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:"- %s" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const newBody = pr.data.body + '\n\n### Commits:\n' + process.env.COMMITS;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: newBody
            });
